# -*- coding: utf-8 -*-
"""EAI MobiHealth 2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AM2JS-YKHen-ooSPwPad5y1llmSV52Ys
"""

# Install wfdb
!pip install wfdb

# Reinstall torch to ensure the CPU-only version (if needed)
!pip uninstall -y torch
!pip install torch==2.6.0 --index-url https://download.pytorch.org/whl/cpu

# Verify torch version
import torch
print(f"Torch version: {torch.__version__}")

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU device: {torch.cuda.get_device_name(0)}")

from google.colab import drive  # Import the necessary module

drive.mount('/content/drive')

# Step 1: Download and Extract PTB-XL Dataset
# Download the single .zip file
!wget -O ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.3.zip https://physionet.org/static/published-projects/ptb-xl/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.3.zip

# Extract the zip file
!unzip -o ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.3.zip -d /content/ptb-xl

# Define the data path (adjust for extracted folder structure)
DATA_PATH = '/content/ptb-xl/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.3'

# Verify the dataset directory
!ls $DATA_PATH

import os
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
import wfdb

# Define the data path (already set in Step 1)
data_path = '/content/ptb-xl/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.3'

class PTBXL_Dataset(Dataset):
    def __init__(self, records, labels, sensitive_attrs):
        self.records = records
        self.labels = labels
        self.sensitive_attrs = sensitive_attrs

    def __len__(self):
        return len(self.records)

    def __getitem__(self, idx):
        signal = self.records[idx]
        label = self.labels[idx]
        sensitive = self.sensitive_attrs[idx]
        return torch.tensor(signal, dtype=torch.float32), torch.tensor(label, dtype=torch.long), torch.tensor(sensitive, dtype=torch.long)

def load_ptbxl_data(data_path, subsample_fraction=0.2):
    metadata_path = os.path.join(data_path, 'ptbxl_database.csv')
    if not os.path.exists(metadata_path):
        raise FileNotFoundError(f"Metadata file not found at {metadata_path}")
    metadata = pd.read_csv(metadata_path)

    # Subsample the dataset
    metadata = metadata.sample(frac=subsample_fraction, random_state=42)
    print(f"Subsampled dataset size: {len(metadata)} records")

    # Filter for MI detection (binary classification)
    mi_codes = ['IMI', 'AMI']
    # Parse scp_codes (stored as string representation of dict)
    import ast
    metadata['scp_codes'] = metadata['scp_codes'].apply(ast.literal_eval)
    metadata['label'] = metadata['scp_codes'].apply(lambda x: 1 if any(code in x for code in mi_codes) else 0)
    if metadata['label'].isnull().any():
        raise ValueError("Found NaN values in labels")
    print("Label distribution:", metadata['label'].value_counts())

    # Handle sex: Ensure no NaN values, map to 0/1
    if metadata['sex'].isnull().any():
        print("Found NaN values in 'sex'. Filling with mode.")
        metadata['sex'] = metadata['sex'].fillna(metadata['sex'].mode()[0])
    metadata['sex'] = metadata['sex'].map({0: 0, 1: 1})
    if metadata['sex'].isnull().any():
        raise ValueError("Failed to map 'sex'. Contains invalid values.")
    print("Sex distribution:", metadata['sex'].value_counts())

    # Handle age: Ensure numeric, handle invalid values
    metadata['age'] = pd.to_numeric(metadata['age'], errors='coerce')

    # Inspect age column before cleaning
    print("Age statistics before cleaning:")
    print("NaN count:", metadata['age'].isnull().sum())
    print("Min age:", metadata['age'].min())
    print("Max age:", metadata['age'].max())
    print("Unique ages:", sorted(metadata['age'].unique()))

    # Handle invalid ages
    if metadata['age'].isnull().any():
        print("Found NaN values in 'age'. Filling with median.")
        median_age = metadata['age'].median()
        metadata['age'] = metadata['age'].fillna(median_age)

    # Clip ages to a reasonable range
    metadata['age'] = metadata['age'].clip(lower=0, upper=120)

    # Inspect age column after clipping
    print("Age statistics after clipping:")
    print("Min age:", metadata['age'].min())
    print("Max age:", metadata['age'].max())
    print("Unique ages after clipping:", sorted(metadata['age'].unique()))

    # Bin age into groups
    metadata['age_group'] = pd.cut(metadata['age'],
                                   bins=[0, 40, 60, 121],
                                   labels=[0, 1, 2],
                                   right=False,
                                   include_lowest=True)

    if metadata['age_group'].isnull().any():
        invalid_rows = metadata[metadata['age_group'].isnull()]
        print("Rows with invalid age_group:", invalid_rows[['age', 'age_group']])
        raise ValueError("Failed to bin 'age'. Contains invalid values after cleaning.")
    print("Age group distribution:", metadata['age_group'].value_counts())

    # Load ECG signals
    signals = []
    labels = []
    sensitive_attrs = []

    for idx, row in metadata.iterrows():
        record_path = os.path.join(data_path, row['filename_lr'])
        try:
            signal, _ = wfdb.rdsamp(record_path)
            signal = (signal - signal.mean(axis=0)) / (signal.std(axis=0) + 1e-8)
            signal = signal[:1000, :]  # Truncate to 1000 samples
            signals.append(signal)
            labels.append(row['label'])
            sensitive_attrs.append([row['sex'], row['age_group']])
        except Exception as e:
            print(f"Error loading {record_path}: {e}")
            continue

    signals = np.array(signals)
    labels = np.array(labels)
    sensitive_attrs = np.array(sensitive_attrs)

    # Final validation
    if np.any(np.isnan(labels)):
        raise ValueError("NaN values found in labels after processing")
    if np.any(np.isnan(sensitive_attrs)):
        raise ValueError("NaN values found in sensitive_attrs after processing")

    return signals, labels, sensitive_attrs

# Load and split data (subsample to 20%)
signals, labels, sensitive_attrs = load_ptbxl_data(data_path, subsample_fraction=0.2)
X_train, X_temp, y_train, y_temp, s_train, s_temp = train_test_split(
    signals, labels, sensitive_attrs, test_size=0.3, stratify=labels, random_state=42
)
X_val, X_test, y_val, y_test, s_val, s_test = train_test_split(
    X_temp, y_temp, s_temp, test_size=0.5, stratify=y_temp, random_state=42
)

# Create datasets and data loaders
train_dataset = PTBXL_Dataset(X_train, y_train, s_train)
val_dataset = PTBXL_Dataset(X_val, y_val, s_val)
test_dataset = PTBXL_Dataset(X_test, y_test, s_test)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=64)
test_loader = DataLoader(test_dataset, batch_size=64)

# Verify the shapes of the data
print(f"Training set size: {len(train_dataset)}")
print(f"Validation set size: {len(val_dataset)}")
print(f"Test set size: {len(test_dataset)}")

# Check a sample batch
for batch in train_loader:
    signals, labels, sensitive = batch
    print(f"Sample batch - Signals shape: {signals.shape}, Labels shape: {labels.shape}, Sensitive attrs shape: {sensitive.shape}")
    break

import torch
import torch.nn as nn


class GradientReversal(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, lambda_):
        ctx.lambda_ = lambda_
        return x.view_as(x)

    @staticmethod
    def backward(ctx, grad_output):
        return -ctx.lambda_ * grad_output, None

class Encoder(nn.Module):
    def __init__(self, input_channels=12, output_dim=128):
        super(Encoder, self).__init__()
        self.model = nn.Sequential(
            nn.Conv1d(input_channels, 64, kernel_size=7, stride=2, padding=3),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Conv1d(64, 128, kernel_size=5, stride=2, padding=2),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Conv1d(128, 256, kernel_size=5, stride=2, padding=2),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.AdaptiveAvgPool1d(1),
            nn.Flatten(),
            nn.Linear(256, output_dim)
        )

    def forward(self, x):
        return self.model(x)

class Classifier(nn.Module):
    def __init__(self, input_dim=128, num_classes=2):
        super(Classifier, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, num_classes)
        )

    def forward(self, x):
        return self.model(x)

class Adversary(nn.Module):
    def __init__(self, input_dim=128, num_classes=2):
        super(Adversary, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, num_classes)
        )

    def forward(self, x, lambda_):
        x = GradientReversal.apply(x, lambda_)
        return self.model(x)

# Instantiate the models
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

encoder = Encoder().to(device)
classifier = Classifier().to(device)
adversary_sex = Adversary(num_classes=2).to(device)  # For sex (0 or 1)
adversary_age = Adversary(num_classes=3).to(device)  # For age_group (0, 1, 2)

# Verify model initialization
print("Encoder:", encoder)
print("Classifier:", classifier)
print("Adversary (Sex):", adversary_sex)
print("Adversary (Age):", adversary_age)

import torch.optim as optim
import torch.nn as nn
from torch.amp import autocast, GradScaler  # Updated import for PyTorch 2.4.0+

# Use existing device and model instances from Step 3
# device, encoder, classifier, adversary_sex, and adversary_age are already defined

# Set up optimizers
optimizer_enc = optim.Adam(encoder.parameters(), lr=0.001)
optimizer_cls = optim.Adam(classifier.parameters(), lr=0.001)
optimizer_adv_sex = optim.Adam(adversary_sex.parameters(), lr=0.001)
optimizer_adv_age = optim.Adam(adversary_age.parameters(), lr=0.001)

# Add class weights to handle imbalance
class_weights_main = torch.tensor([1.0, 5.0]).to(device)  # Higher weight for MI (class 1) - for main classifier
class_weights_sex = torch.tensor([1.0, 1.0]).to(device)  # Equal weights for sex - for sex adversary
class_weights_age = torch.tensor([1.0, 1.0, 1.0]).to(device)  # Equal weights for age groups - for age adversary

# Use separate criteria for the main classifier, sex adversary, and age adversary
criterion_main = nn.CrossEntropyLoss(weight=class_weights_main)
criterion_sex = nn.CrossEntropyLoss(weight=class_weights_sex)
criterion_age = nn.CrossEntropyLoss(weight=class_weights_age)

# For mixed precision training
scaler = GradScaler('cuda')  # Updated for PyTorch 2.4.0+

# Define the training function
def train_epoch(encoder, classifier, adversary_sex, adversary_age, loader, lambda_, epoch, num_epochs):
    encoder.train()
    classifier.train()
    adversary_sex.train()
    adversary_age.train()

    total_loss = 0
    task_loss_total = 0
    adv_loss_sex_total = 0
    adv_loss_age_total = 0

    for signals, labels, sensitive in loader:
        signals = signals.permute(0, 2, 1).to(device)  # [batch, 1000, 12] -> [batch, 12, 1000]
        labels = labels.to(device)
        sex = sensitive[:, 0].to(device)
        age = sensitive[:, 1].to(device)

        # Forward pass for task
        with autocast('cuda'):  # Updated for PyTorch 2.4.0+
            z = encoder(signals)
            task_pred = classifier(z)
            adv_pred_sex = adversary_sex(z, lambda_)
            adv_pred_age = adversary_age(z, lambda_)

            task_loss = criterion_main(task_pred, labels)  # Use criterion_main for MI classification
            adv_loss_sex = criterion_sex(adv_pred_sex, sex)  # Use criterion_sex for sex adversary
            adv_loss_age = criterion_age(adv_pred_age, age)  # Use criterion_age for age adversary
            total_adv_loss = adv_loss_sex + adv_loss_age
            loss = task_loss - lambda_ * total_adv_loss

        # Backward pass for encoder and classifier
        optimizer_enc.zero_grad()
        optimizer_cls.zero_grad()
        scaler.scale(loss).backward()
        scaler.step(optimizer_enc)
        scaler.step(optimizer_cls)
        scaler.update()

        # Backward pass for adversary_sex
        with autocast('cuda'):  # Updated for PyTorch 2.4.0+
            z_sex = encoder(signals.detach())
            adv_pred_sex = adversary_sex(z_sex, lambda_)
            adv_loss_sex = criterion_sex(adv_pred_sex, sex)  # Use criterion_sex

        optimizer_adv_sex.zero_grad()
        scaler.scale(adv_loss_sex).backward()
        scaler.step(optimizer_adv_sex)
        scaler.update()

        # Backward pass for adversary_age
        with autocast('cuda'):  # Updated for PyTorch 2.4.0+
            z_age = encoder(signals.detach())
            adv_pred_age = adversary_age(z_age, lambda_)
            adv_loss_age = criterion_age(adv_pred_age, age)  # Use criterion_age

        optimizer_adv_age.zero_grad()
        scaler.scale(adv_loss_age).backward()
        scaler.step(optimizer_adv_age)
        scaler.update()

        # Accumulate losses for logging
        total_loss += loss.item()
        task_loss_total += task_loss.item()
        adv_loss_sex_total += adv_loss_sex.item()
        adv_loss_age_total += adv_loss_age.item()

    avg_total_loss = total_loss / len(loader)
    avg_task_loss = task_loss_total / len(loader)
    avg_adv_loss_sex = adv_loss_sex_total / len(loader)
    avg_adv_loss_age = adv_loss_age_total / len(loader)

    print(f'Epoch [{epoch+1}/{num_epochs}] Loss: {avg_total_loss:.4f}, '
          f'Task: {avg_task_loss:.4f}, '
          f'Adv_Sex: {avg_adv_loss_sex:.4f}, '
          f'Adv_Age: {avg_adv_loss_age:.4f}')

    return avg_total_loss, avg_task_loss, avg_adv_loss_sex, avg_adv_loss_age

# Test one epoch to verify the training loop
lambda_ = 0.1  # Example lambda value
num_epochs = 1  # Run for 1 epoch to test
train_epoch(encoder, classifier, adversary_sex, adversary_age, train_loader, lambda_, 0, num_epochs)

num_epochs = 10
lambda_max = 0.1
for epoch in range(num_epochs):
    lambda_ = lambda_max * min(1.0, (epoch + 1) / 10.0)
    train_epoch(encoder, classifier, adversary_sex, adversary_age, train_loader, lambda_, epoch, num_epochs)

from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
import numpy as np

def evaluate(encoder, classifier, loader):
    encoder.eval()
    classifier.eval()

    preds = []
    labels = []
    sex_attrs = []
    age_attrs = []

    with torch.no_grad():
        for signals, lbls, sensitive in loader:
            signals = signals.permute(0, 2, 1).to(device)
            z = encoder(signals)
            pred = classifier(z)
            preds.append(torch.softmax(pred, dim=1).cpu().numpy())
            labels.append(lbls.numpy())
            sex_attrs.append(sensitive[:, 0].numpy())
            age_attrs.append(sensitive[:, 1].numpy())

    preds = np.concatenate(preds)
    labels = np.concatenate(labels)
    sex_attrs = np.concatenate(sex_attrs)
    age_attrs = np.concatenate(age_attrs)

    y_pred = np.argmax(preds, axis=1)
    y_score = preds[:, 1]
    acc = accuracy_score(labels, y_pred)
    f1 = f1_score(labels, y_pred)
    auroc = roc_auc_score(labels, y_score)

    def demographic_parity_diff(y_pred, s, num_classes):
        probs = []
        for i in range(num_classes):
            prob = np.mean(y_pred[s == i]) if np.sum(s == i) > 0 else 0
            probs.append(prob)
        return np.max(probs) - np.min(probs) if probs else 0

    def equalized_odds_diff(y_pred, y_true, s, num_classes):
        tprs, fprs = [], []
        for i in range(num_classes):
            mask_true = (y_true == 1) & (s == i)
            mask_false = (y_true == 0) & (s == i)
            tpr = np.mean(y_pred[mask_true]) if np.sum(mask_true) > 0 else 0
            fpr = np.mean(y_pred[mask_false]) if np.sum(mask_false) > 0 else 0
            tprs.append(tpr)
            fprs.append(fpr)
        tpr_diff = np.max(tprs) - np.min(tprs) if tprs else 0
        fpr_diff = np.max(fprs) - np.min(fprs) if fprs else 0
        return max(tpr_diff, fpr_diff)

    def disparate_impact(y_pred, s, num_classes):
        probs = []
        for i in range(num_classes):
            prob = np.mean(y_pred[s == i]) if np.sum(s == i) > 0 else 0
            probs.append(prob)
        probs = [p for p in probs if p > 0]  # Avoid division by zero
        return min(probs) / max(probs) if probs else 0

    # Compute fairness metrics for sex (2 classes: 0, 1)
    dpd_sex = demographic_parity_diff(y_pred, sex_attrs, num_classes=2)
    eod_sex = equalized_odds_diff(y_pred, labels, sex_attrs, num_classes=2)
    di_sex = disparate_impact(y_pred, sex_attrs, num_classes=2)

    # Compute fairness metrics for age (3 classes: 0, 1, 2)
    dpd_age = demographic_parity_diff(y_pred, age_attrs, num_classes=3)
    eod_age = equalized_odds_diff(y_pred, labels, age_attrs, num_classes=3)
    di_age = disparate_impact(y_pred, age_attrs, num_classes=3)

    return {
        'AUROC': auroc,
        'Accuracy': acc,
        'F1': f1,
        'DPD_Sex': dpd_sex,
        'EOD_Sex': eod_sex,
        'DI_Sex': di_sex,
        'DPD_Age': dpd_age,
        'EOD_Age': eod_age,
        'DI_Age': di_age
    }

# Evaluate on test set
metrics = evaluate(encoder, classifier, test_loader)
print("Test Metrics:", metrics)

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

def visualize_latent_space(encoder, loader):
    encoder.eval()
    z_list = []
    labels = []
    sex_attrs = []
    age_attrs = []

    with torch.no_grad():
        for signals, lbls, sensitive in loader:
            signals = signals.permute(0, 2, 1).to(device)
            z = encoder(signals)
            z_list.append(z.cpu().numpy())
            labels.append(lbls.numpy())
            sex_attrs.append(sensitive[:, 0].numpy())
            age_attrs.append(sensitive[:, 1].numpy())

    z = np.concatenate(z_list)
    labels = np.concatenate(labels)
    sex_attrs = np.concatenate(sex_attrs)
    age_attrs = np.concatenate(age_attrs)

    z_2d = TSNE(n_components=2, random_state=42).fit_transform(z)

    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    for s in np.unique(sex_attrs):
        mask = sex_attrs == s
        plt.scatter(z_2d[mask, 0], z_2d[mask, 1], label=f'Sex {s}', alpha=0.6)
    plt.title("Latent Space by Sex")
    plt.legend()

    plt.subplot(1, 2, 2)
    for a in np.unique(age_attrs):
        mask = age_attrs == a
        plt.scatter(z_2d[mask, 0], z_2d[mask, 1], label=f'Age Group {a}', alpha=0.6)
    plt.title("Latent Space by Age Group")
    plt.legend()

    plt.show()

visualize_latent_space(encoder, test_loader)

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch

def extract_latents(encoder, loader):
    encoder.eval()
    latents = []
    sex_attrs = []
    age_attrs = []
    with torch.no_grad():
        for signals, _, sensitive in loader:
            signals = signals.permute(0, 2, 1).to(device)
            z = encoder(signals)
            latents.append(z.cpu().numpy())
            sex_attrs.append(sensitive[:, 0].numpy())
            age_attrs.append(sensitive[:, 1].numpy())
    return (
        np.concatenate(latents),
        np.concatenate(sex_attrs),
        np.concatenate(age_attrs)
    )

# Get latent features and attributes from the test set
latents, sex, age_group = extract_latents(encoder, test_loader)

# Apply t-SNE
tsne = TSNE(n_components=2, random_state=42)
tsne_proj = tsne.fit_transform(latents)

# Plot by sex
plt.figure(figsize=(8, 6))
sns.scatterplot(x=tsne_proj[:, 0], y=tsne_proj[:, 1], hue=sex, palette="Set2")
plt.title("t-SNE of Latent Representations (After Debiasing) — Colored by Sex")
plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")
plt.legend(title="Sex", labels=["Male", "Female"])
plt.tight_layout()
plt.savefig("tsne_debiased_sex.png")
plt.show()

# Plot by age group
plt.figure(figsize=(8, 6))
sns.scatterplot(x=tsne_proj[:, 0], y=tsne_proj[:, 1], hue=age_group, palette="Set1")
plt.title("t-SNE of Latent Representations (After Debiasing) — Colored by Age Group")
plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")
plt.legend(title="Age Group", labels=["<40", "40–59", "60+"])
plt.tight_layout()
plt.savefig("tsne_debiased_age.png")
plt.show()

import pandas as pd
import wfdb
import numpy as np
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader
import torch
import ast

# Define data path
DATA_PATH = '/content/ptb-xl/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.3'

class ECGDataset(Dataset):
    def __init__(self, signals, labels, sexes, ages):
        self.signals = torch.tensor(signals, dtype=torch.float32)
        self.labels = torch.tensor(labels, dtype=torch.long)  # Labels should be long for CrossEntropyLoss
        self.sexes = torch.tensor(sexes, dtype=torch.long)
        self.ages = torch.tensor(ages, dtype=torch.long)
    def __len__(self): return len(self.signals)
    def __getitem__(self, idx):
        return self.signals[idx], self.labels[idx], self.sexes[idx], self.ages[idx]

def load_ptbxl_data_robust(data_path, subsample_fraction=0.2):
    metadata_path = os.path.join(data_path, 'ptbxl_database.csv')
    if not os.path.exists(metadata_path):
        raise FileNotFoundError(f"Metadata file not found at {metadata_path}")
    metadata = pd.read_csv(metadata_path)

    # Subsample the dataset
    metadata = metadata.sample(frac=subsample_fraction, random_state=42)
    print(f"Subsampled dataset size: {len(metadata)} records")

    # Filter for MI detection (binary classification)
    mi_codes = ['IMI', 'AMI']
    # Parse scp_codes (stored as string representation of dict)
    metadata['scp_codes'] = metadata['scp_codes'].apply(ast.literal_eval)
    metadata['label'] = metadata['scp_codes'].apply(lambda x: 1 if any(code in x for code in mi_codes) else 0)
    if metadata['label'].isnull().any():
        raise ValueError("Found NaN values in labels")
    print("Label distribution:", metadata['label'].value_counts())

    # Handle sex: Ensure no NaN values, map to 0/1
    if metadata['sex'].isnull().any():
        print("Found NaN values in 'sex'. Filling with mode.")
        metadata['sex'] = metadata['sex'].fillna(metadata['sex'].mode()[0])
    metadata['sex'] = metadata['sex'].map({0: 0, 1: 1})
    if metadata['sex'].isnull().any():
        raise ValueError("Failed to map 'sex'. Contains invalid values.")
    print("Sex distribution:", metadata['sex'].value_counts())

    # Handle age: Ensure numeric, handle invalid values
    metadata['age'] = pd.to_numeric(metadata['age'], errors='coerce')

    # Handle invalid ages
    if metadata['age'].isnull().any():
        print("Found NaN values in 'age'. Filling with median.")
        median_age = metadata['age'].median()
        metadata['age'] = metadata['age'].fillna(median_age)

    # Clip ages to a reasonable range
    metadata['age'] = metadata['age'].clip(lower=0, upper=120)

    # Bin age into groups
    metadata['age_group'] = pd.cut(metadata['age'],
                                   bins=[0, 40, 60, 121],
                                   labels=[0, 1, 2],
                                   right=False,
                                   include_lowest=True)

    if metadata['age_group'].isnull().any():
        invalid_rows = metadata[metadata['age_group'].isnull()]
        print("Rows with invalid age_group:", invalid_rows[['age', 'age_group']])
        raise ValueError("Failed to bin 'age'. Contains invalid values after cleaning.")
    print("Age group distribution:", metadata['age_group'].value_counts())

    # Load ECG signals
    signals = []
    labels = []
    sexes = []
    ages = []

    for idx, row in metadata.iterrows():
        record_path = os.path.join(data_path, row['filename_lr'])
        try:
            signal, _ = wfdb.rdsamp(record_path)
            signal = (signal - signal.mean(axis=0)) / (signal.std(axis=0) + 1e-8)
            signal = signal[:1000, :]  # Truncate to 1000 samples
            signals.append(signal)
            labels.append(row['label'])
            sexes.append(row['sex'])
            ages.append(row['age_group'])
        except Exception as e:
            print(f"Error loading {record_path}: {e}")
            continue

    signals = np.array(signals)
    labels = np.array(labels)
    sexes = np.array(sexes)
    ages = np.array(ages)

    # Final validation
    if np.any(np.isnan(labels)):
        raise ValueError("NaN values found in labels after processing")
    if np.any(np.isnan(sexes)):
        raise ValueError("NaN values found in sexes after processing")
    if np.any(np.isnan(ages)):
         raise ValueError("NaN values found in ages after processing")

    return signals, labels, sexes, ages

# Load and split data (subsample to 20%)
signals, labels, sexes, ages = load_ptbxl_data_robust(DATA_PATH, subsample_fraction=0.2)

# Split dataset
X_train, X_temp, y_train, y_temp, sex_train, sex_temp, age_train, age_temp = train_test_split(
    signals, labels, sexes, ages, test_size=0.3, stratify=labels, random_state=42)
X_val, X_test, y_val, y_test, sex_val, sex_test, age_val, age_test = train_test_split(
    X_temp, y_temp, sex_temp, age_temp, test_size=0.5, stratify=y_temp, random_state=42)

# Custom Dataset
train_dataset = ECGDataset(X_train, y_train, sex_train, age_train)
val_dataset = ECGDataset(X_val, y_val, sex_val, age_val)
test_dataset = ECGDataset(X_test, y_test, sex_test, age_test)

train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=128)
test_loader = DataLoader(test_dataset, batch_size=128)

from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score, accuracy_score, f1_score
import torch
import torch.nn as nn
import torch.optim as optim

# Define model (as in original)
class GradientReversalLayer(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, lambda_):
        ctx.lambda_ = lambda_
        return x.view_as(x)

    @staticmethod
    def backward(ctx, grad_output):
        return -ctx.lambda_ * grad_output, None

class Encoder(nn.Module):
    def __init__(self, input_channels=12, output_dim=128):
        super(Encoder, self).__init__()
        self.model = nn.Sequential(
            nn.Conv1d(input_channels, 64, kernel_size=7, stride=2, padding=3),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Conv1d(64, 128, kernel_size=5, stride=2, padding=2),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Conv1d(128, 256, kernel_size=5, stride=2, padding=2),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.AdaptiveAvgPool1d(1),
            nn.Flatten(),
            nn.Linear(256, output_dim)
        )

    def forward(self, x):
        return self.model(x)

class Classifier(nn.Module):
    def __init__(self, input_dim=128, num_classes=2):
        super(Classifier, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, num_classes)
        )

    def forward(self, x):
        return self.model(x)

class Adversary(nn.Module):
    def __init__(self, input_dim=128, num_classes=2):
        super(Adversary, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, num_classes)
        )

    def forward(self, x, lambda_):
        x = GradientReversalLayer.apply(x, lambda_)
        return self.model(x)

# Training function
def train_model(encoder, classifier, adv_sex, adv_age, train_loader, device, lambda_val=0.3, epochs=20):
    optimizer = optim.Adam(list(encoder.parameters()) + list(classifier.parameters()) +
                          list(adv_sex.parameters()) + list(adv_age.parameters()), lr=0.001)
    criterion_class = nn.CrossEntropyLoss() # Changed to CrossEntropyLoss
    criterion_adv_sex = nn.CrossEntropyLoss() # Assuming 2 classes for sex adversary
    criterion_adv_age = nn.CrossEntropyLoss() # Assuming 3 classes for age adversary


    for epoch in range(epochs):
        encoder.train()
        classifier.train()
        adv_sex.train()
        adv_age.train()
        for signals, labels, sexes, ages in train_loader:
            signals = signals.permute(0, 2, 1).to(device)
            labels, sexes, ages = labels.to(device), sexes.to(device), ages.to(device)
            optimizer.zero_grad()

            # Train classifier and encoder to minimize main task loss and maximize adversary loss
            z = encoder(signals)
            pred = classifier(z) # Removed .squeeze()
            # Ensure labels are float for BCELoss
            loss_class = criterion_class(pred, labels)

            pred_sex = adv_sex(GradientReversalLayer.apply(z, lambda_val), lambda_val)
            pred_age = adv_age(GradientReversalLayer.apply(z, lambda_val), lambda_val)
            loss_adv = criterion_adv_sex(pred_sex, sexes) + criterion_adv_age(pred_age, ages)
            loss = loss_class - lambda_val * loss_adv

            loss.backward()
            optimizer.step()

            # Train adversaries to minimize adversary loss
            optimizer.zero_grad()
            z = encoder(signals.detach())  # Detach to prevent gradients flowing to encoder
            pred_sex = adv_sex(z, lambda_val) # Added lambda_val
            pred_age = adv_age(z, lambda_val) # Added lambda_val
            loss_adv = criterion_adv_sex(pred_sex, sexes) + criterion_adv_age(pred_age, ages)

            loss_adv.backward()
            optimizer.step()


    return encoder, classifier

# Evaluation function
def evaluate_model(encoder, classifier, test_loader, device):
    encoder.eval()
    classifier.eval()
    preds, truths = [], []
    sex_attrs, age_attrs = [], [] # Collect sensitive attributes as well

    with torch.no_grad():
        for signals, labels, sexes, ages in test_loader:
            signals = signals.permute(0, 2, 1).to(device)
            z = encoder(signals)
            pred = classifier(z)
            preds.extend(torch.softmax(pred, dim=1)[:, 1].cpu().numpy()) # Use softmax for probabilities and take class 1
            truths.extend(labels.cpu().numpy())
            sex_attrs.extend(sexes.cpu().numpy())
            age_attrs.extend(ages.cpu().numpy())


    auroc = roc_auc_score(truths, preds)
    preds_bin = (np.array(preds) > 0.5).astype(int)
    acc = accuracy_score(truths, preds_bin)
    f1 = f1_score(truths, preds_bin)

    # Fairness metrics (simplified DPD for sex)
    def demographic_parity_diff(y_pred, s, num_classes):
        probs = []
        for i in range(num_classes):
            prob = np.mean(y_pred[s == i]) if np.sum(s == i) > 0 else 0
            probs.append(prob)
        return np.max(probs) - np.min(probs) if probs else 0

    dpd_sex = demographic_parity_diff(preds_bin, np.array(sex_attrs), num_classes=2)
    dpd_age = demographic_parity_diff(preds_bin, np.array(age_attrs), num_classes=3)

    return auroc, acc, f1, dpd_sex, dpd_age

# 5-fold CV
kf = KFold(n_splits=5, shuffle=True, random_state=42)
aurocs, accs, f1s, dpds_sex, dpds_age = [], [], [], [], []

# Ensure signals, labels, sexes, ages are defined from the previous cell execution
# signals, labels, sexes, ages = load_ptbxl_data_robust(DATA_PATH, subsample_fraction=0.2) # This line is already executed in the previous cell

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu') # Define device here

for fold, (train_idx, test_idx) in enumerate(kf.split(signals)):
    train_dataset = ECGDataset(signals[train_idx], labels[train_idx], sexes[train_idx], ages[train_idx])
    test_dataset = ECGDataset(signals[test_idx], labels[test_idx], sexes[test_idx], ages[test_idx])
    train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=128)

    encoder = Encoder().to(device)
    classifier = Classifier().to(device)
    adv_sex = Adversary(num_classes=2).to(device)  # Specify num_classes for sex adversary
    adv_age = Adversary(num_classes=3).to(device)  # Specify num_classes for age adversary

    encoder, classifier = train_model(encoder, classifier, adv_sex, adv_age, train_loader, device)
    auroc, acc, f1, dpd_sex, dpd_age = evaluate_model(encoder, classifier, test_loader, device)
    aurocs.append(auroc)
    accs.append(acc)
    f1s.append(f1)
    dpds_sex.append(dpd_sex)
    dpds_age.append(dpd_age)

    print(f"Fold {fold+1}: AUROC={auroc:.4f}, Acc={acc:.4f}, F1={f1:.4f}, DPD_Sex={dpd_sex:.4f}, DPD_Age={dpd_age:.4f}")

print(f"Mean AUROC: {np.mean(aurocs):.4f} ± {np.std(aurocs):.4f}")
print(f"Mean DPD_Sex: {np.mean(dpds_sex):.4f} ± {np.std(dpds_sex):.4f}")
print(f"Mean DPD_Age: {np.mean(dpds_age):.4f} ± {np.std(dpds_age):.4f}")

# Demographics-as-Features Baseline
class EncoderWithDemog(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = Encoder().to(device)
        self.fc = nn.Linear(128 + 2 + 3, 128)  # Concatenate encoder output (128), sex (2) + age (3) one-hot
    def forward(self, x, sex, age):
        z = self.encoder(x)
        sex_onehot = torch.nn.functional.one_hot(sex, 2).float().to(device)
        age_onehot = torch.nn.functional.one_hot(age, 3).float().to(device)
        z_cat = torch.cat([z, sex_onehot, age_onehot], dim=1)
        return self.fc(z_cat)

# Group-Specific Model (example for male)
def train_group_specific(train_loader, group_attribute, group_val):
    encoder = Encoder().to(device)
    classifier = Classifier().to(device)
    optimizer = optim.Adam(list(encoder.parameters()) + list(classifier.parameters()), lr=0.001)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(20):
        encoder.train()
        classifier.train()
        for signals, labels, sexes, ages in train_loader:
            if group_attribute == 'sex':
                mask = (sexes == group_val)
            elif group_attribute == 'age':
                mask = (ages == group_val)
            else:
                raise ValueError("Invalid group_attribute")

            if mask.sum() == 0:
                continue

            signals = signals[mask].permute(0, 2, 1).to(device)
            labels = labels[mask].to(device)

            optimizer.zero_grad()
            z = encoder(signals)
            pred = classifier(z)
            loss = criterion(pred, labels)
            loss.backward()
            optimizer.step()
    return encoder, classifier


# Evaluation function for baselines
def evaluate_baseline_model(encoder, classifier, test_loader, device, baseline_type=None):
    encoder.eval()
    classifier.eval()
    preds, truths = [], []
    sex_attrs, age_attrs = [], []

    with torch.no_grad():
        for signals, labels, sexes, ages in test_loader:
            signals = signals.permute(0, 2, 1).to(device)
            sexes_gpu = sexes.to(device)
            ages_gpu = ages.to(device)

            if baseline_type == 'DemogFeatures':
                z = encoder(signals, sexes_gpu, ages_gpu)
            else: # GroupSpecific
                z = encoder(signals)

            pred = classifier(z)
            preds.extend(torch.softmax(pred, dim=1)[:, 1].cpu().numpy())
            truths.extend(labels.cpu().numpy())
            sex_attrs.extend(sexes.cpu().numpy())
            age_attrs.extend(ages.cpu().numpy())

    auroc = roc_auc_score(truths, preds)
    preds_bin = (np.array(preds) > 0.5).astype(int)
    acc = accuracy_score(truths, preds_bin)
    f1 = f1_score(truths, preds_bin)

    def demographic_parity_diff(y_pred, s, num_classes):
        probs = []
        for i in range(num_classes):
            prob = np.mean(y_pred[s == i]) if np.sum(s == i) > 0 else 0
            probs.append(prob)
        return np.max(probs) - np.min(probs) if probs else 0

    dpd_sex = demographic_parity_diff(preds_bin, np.array(sex_attrs), num_classes=2)
    dpd_age = demographic_parity_diff(preds_bin, np.array(age_attrs), num_classes=3)

    return auroc, acc, f1, dpd_sex, dpd_age


# Evaluate baselines
baselines = ['DemogFeatures', 'GroupSpecific_Sex_0', 'GroupSpecific_Sex_1', 'GroupSpecific_Age_0', 'GroupSpecific_Age_1', 'GroupSpecific_Age_2']
results = []

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu') # Define device here

for baseline in baselines:
    print(f"Training baseline: {baseline}")
    if baseline == 'DemogFeatures':
        encoder = EncoderWithDemog().to(device)
        classifier = Classifier().to(device)
        optimizer = optim.Adam(list(encoder.parameters()) + list(classifier.parameters()), lr=0.001)
        criterion = nn.CrossEntropyLoss()

        for epoch in range(20):
            encoder.train()
            classifier.train()
            for signals, labels, sexes, ages in train_loader:
                signals = signals.permute(0, 2, 1).to(device)
                labels = labels.to(device)
                sexes_gpu = sexes.to(device)
                ages_gpu = ages.to(device)

                optimizer.zero_grad()
                z = encoder(signals, sexes_gpu, ages_gpu)
                pred = classifier(z)
                loss = criterion(pred, labels)
                loss.backward()
                optimizer.step()
        auroc, acc, f1, dpd_sex, dpd_age = evaluate_baseline_model(encoder, classifier, test_loader, device, baseline_type='DemogFeatures')
    else:
        parts = baseline.split('_')
        group_attribute = parts[1].lower() # Convert to lowercase
        group_val = int(parts[2])
        encoder, classifier = train_group_specific(train_loader, group_attribute, group_val)
        auroc, acc, f1, dpd_sex, dpd_age = evaluate_baseline_model(encoder, classifier, test_loader, device, baseline_type='GroupSpecific')

    results.append({'Method': baseline, 'AUROC': auroc, 'Acc': acc, 'F1': f1, 'DPD_Sex': dpd_sex, 'DPD_Age': dpd_age})

# Print results
print("\nBaseline Results:")
for res in results:
    print(f"{res['Method']}: AUROC={res['AUROC']:.4f}, Acc={res['Acc']:.4f}, F1={res['F1']:.4f}, DPD_Sex={res['DPD_Sex']:.4f}, DPD_Age={res['DPD_Age']:.4f}")

# Note: AdvFair/GroupDRO require specific implementations; adapt from their papers [13, 14]

lambda_values = [0.0, 0.1, 0.3, 0.5, 0.7]
ablation_results = []

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu') # Define device here

for lambda_val in lambda_values:
    encoder = Encoder().to(device) # Use device
    classifier = Classifier().to(device) # Use device
    adv_sex = Adversary(num_classes=2).to(device) # Use device, specify num_classes
    adv_age = Adversary(num_classes=3).to(device) # Use device, specify num_classes

    # Assuming train_model is defined and takes device as argument
    encoder, classifier = train_model(encoder, classifier, adv_sex, adv_age, train_loader, device, lambda_val)
    # Assuming evaluate_model is defined and takes device as argument
    auroc, acc, f1, dpd_sex, dpd_age = evaluate_model(encoder, classifier, test_loader, device)
    ablation_results.append({'Lambda': lambda_val, 'AUROC': auroc, 'DPD_Sex': dpd_sex, 'DPD_Age': dpd_age}) # Include DPD_Age
    print(f"Lambda={lambda_val}: AUROC={auroc:.4f}, DPD_Sex={dpd_sex:.4f}, DPD_Age={dpd_age:.4f}") # Print DPD_Age


# Plot ablation
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6)) # Increase figure size for better readability
plt.plot([r['Lambda'] for r in ablation_results], [r['AUROC'] for r in ablation_results], label='AUROC', marker='o') # Add markers
plt.plot([r['Lambda'] for r in ablation_results], [r['DPD_Sex'] for r in ablation_results], label='DPD_Sex', marker='o') # Add markers
plt.plot([r['Lambda'] for r in ablation_results], [r['DPD_Age'] for r in ablation_results], label='DPD_Age', marker='o') # Plot DPD_Age
plt.xlabel('Lambda')
plt.ylabel('Metric Value') # Add ylabel
plt.title('Ablation Study: AUROC and DPD vs. Lambda') # Add title
plt.legend()
plt.grid(True) # Add grid
plt.savefig('ablation_lambda.png')
plt.show() # Show plot

from sklearn.manifold import TSNE
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import roc_curve, roc_auc_score
from IPython import display # Import display
import pandas as pd # Import pandas for data loading
import wfdb # Import wfdb for data loading
import os # Import os for path joining
import ast # Import ast for literal_eval
from sklearn.model_selection import train_test_split # Import train_test_split
from torch.utils.data import Dataset, DataLoader # Import Dataset and DataLoader

# Define data path - Copied from previous cell
DATA_PATH = '/content/ptb-xl/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.3'

# Custom Dataset class - Copied from previous cell
class ECGDataset(Dataset):
    def __init__(self, signals, labels, sexes, ages):
        self.signals = torch.tensor(signals, dtype=torch.float32)
        self.labels = torch.tensor(labels, dtype=torch.long)  # Labels should be long for CrossEntropyLoss
        self.sexes = torch.tensor(sexes, dtype=torch.long)
        self.ages = torch.tensor(ages, dtype=torch.long)
    def __len__(self): return len(self.signals)
    def __getitem__(self, idx):
        return self.signals[idx], self.labels[idx], self.sexes[idx], self.ages[idx]

# Data loading function - Copied from previous cell
def load_ptbxl_data_robust(data_path, subsample_fraction=0.2):
    metadata_path = os.path.join(data_path, 'ptbxl_database.csv')
    if not os.path.exists(metadata_path):
        raise FileNotFoundError(f"Metadata file not found at {metadata_path}")
    metadata = pd.read_csv(metadata_path)

    # Subsample the dataset
    metadata = metadata.sample(frac=subsample_fraction, random_state=42)
    print(f"Subsampled dataset size: {len(metadata)} records")

    # Filter for MI detection (binary classification)
    mi_codes = ['IMI', 'AMI']
    # Parse scp_codes (stored as string representation of dict)
    metadata['scp_codes'] = metadata['scp_codes'].apply(ast.literal_eval)
    metadata['label'] = metadata['scp_codes'].apply(lambda x: 1 if any(code in x for code in mi_codes) else 0)
    if metadata['label'].isnull().any():
        raise ValueError("Found NaN values in labels")
    print("Label distribution:", metadata['label'].value_counts())

    # Handle sex: Ensure no NaN values, map to 0/1
    if metadata['sex'].isnull().any():
        print("Found NaN values in 'sex'. Filling with mode.")
        metadata['sex'] = metadata['sex'].fillna(metadata['sex'].mode()[0])
    metadata['sex'] = metadata['sex'].map({0: 0, 1: 1})
    if metadata['sex'].isnull().any():
        raise ValueError("Failed to map 'sex'. Contains invalid values.")
    print("Sex distribution:", metadata['sex'].value_counts())

    # Handle age: Ensure numeric, handle invalid values
    metadata['age'] = pd.to_numeric(metadata['age'], errors='coerce')

    # Handle invalid ages
    if metadata['age'].isnull().any():
        print("Found NaN values in 'age'. Filling with median.")
        median_age = metadata['age'].median()
        metadata['age'] = metadata['age'].fillna(median_age)

    # Clip ages to a reasonable range
    metadata['age'] = metadata['age'].clip(lower=0, upper=120)

    # Bin age into groups
    metadata['age_group'] = pd.cut(metadata['age'],
                                   bins=[0, 40, 60, 121],
                                   labels=[0, 1, 2],
                                   right=False,
                                   include_lowest=True)

    if metadata['age_group'].isnull().any():
        invalid_rows = metadata[metadata['age_group'].isnull()]
        print("Rows with invalid age_group:", invalid_rows[['age', 'age_group']])
        raise ValueError("Failed to bin 'age'. Contains invalid values after cleaning.")
    print("Age group distribution:", metadata['age_group'].value_counts())

    # Load ECG signals
    signals = []
    labels = []
    sexes = []
    ages = []

    for idx, row in metadata.iterrows():
        record_path = os.path.join(data_path, row['filename_lr'])
        try:
            signal, _ = wfdb.rdsamp(record_path)
            signal = (signal - signal.mean(axis=0)) / (signal.std(axis=0) + 1e-8) # Fixed error here
            signal = signal[:1000, :]  # Truncate to 1000 samples
            signals.append(signal)
            labels.append(row['label'])
            sexes.append(row['sex'])
            ages.append(row['age_group'])
        except Exception as e:
            print(f"Error loading {record_path}: {e}")
            continue

    signals = np.array(signals)
    labels = np.array(labels)
    sexes = np.array(sexes)
    ages = np.array(ages)

    # Final validation
    if np.any(np.isnan(labels)):
        raise ValueError("NaN values found in labels after processing")
    if np.any(np.isnan(sexes)):
        raise ValueError("NaN values found in sexes after processing")
    if np.any(np.isnan(ages)):
         raise ValueError("NaN values found in ages after processing")

    return signals, labels, sexes, ages

# Define model (as in original) - Copied from previous cell
class GradientReversalLayer(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, lambda_):
        ctx.lambda_ = lambda_
        return x.view_as(x)

    @staticmethod
    def backward(ctx, grad_output):
        return -ctx.lambda_ * grad_output, None

class Encoder(nn.Module):
    def __init__(self, input_channels=12, output_dim=128):
        super(Encoder, self).__init__()
        self.model = nn.Sequential(
            nn.Conv1d(input_channels, 64, kernel_size=7, stride=2, padding=3),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Conv1d(64, 128, kernel_size=5, stride=2, padding=2),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Conv1d(128, 256, kernel_size=5, stride=2, padding=2),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.AdaptiveAvgPool1d(1),
            nn.Flatten(),
            nn.Linear(256, output_dim)
        )

    def forward(self, x):
        return self.model(x)

class Classifier(nn.Module):
    def __init__(self, input_dim=128, num_classes=2):
        super(Classifier, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, num_classes)
        )

    def forward(self, x):
        return self.model(x)

class Adversary(nn.Module):
    def __init__(self, input_dim=128, num_classes=2):
        super(Adversary, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, num_classes)
        )

    def forward(self, x, lambda_):
        x = GradientReversalLayer.apply(x, lambda_)
        return self.model(x)

# Training function - Copied from previous cell
def train_model(encoder, classifier, adv_sex, adv_age, train_loader, device, lambda_val=0.3, epochs=20):
    optimizer = optim.Adam(list(encoder.parameters()) + list(classifier.parameters()) +
                          list(adv_sex.parameters()) + list(adv_age.parameters()), lr=0.001)
    criterion_class = nn.CrossEntropyLoss() # Changed to CrossEntropyLoss
    criterion_adv_sex = nn.CrossEntropyLoss() # Assuming 2 classes for sex adversary
    criterion_adv_age = nn.CrossEntropyLoss() # Assuming 3 classes for age adversary


    for epoch in range(epochs):
        encoder.train()
        classifier.train()
        adv_sex.train()
        adv_age.train()
        for signals, labels, sexes, ages in train_loader:
            signals = signals.permute(0, 2, 1).to(device)
            labels, sexes, ages = labels.to(device), sexes.to(device), ages.to(device)
            optimizer.zero_grad()

            # Train classifier and encoder to minimize main task loss and maximize adversary loss
            z = encoder(signals)
            pred = classifier(z) # Removed .squeeze()
            # Ensure labels are float for BCELoss
            loss_class = criterion_class(pred, labels)

            pred_sex = adv_sex(GradientReversalLayer.apply(z, lambda_val), lambda_val)
            pred_age = adv_age(GradientReversalLayer.apply(z, lambda_val), lambda_val)
            loss_adv = criterion_adv_sex(pred_sex, sexes) + criterion_adv_age(pred_age, ages)
            loss = loss_class - lambda_val * loss_adv

            loss.backward()
            optimizer.step()

            # Train adversaries to minimize adversary loss
            optimizer.zero_grad()
            z = encoder(signals.detach())  # Detach to prevent gradients flowing to encoder
            pred_sex = adv_sex(z, lambda_val) # Added lambda_val
            pred_age = adv_age(z, lambda_val) # Added lambda_val
            loss_adv = criterion_adv_sex(pred_sex, sexes) + criterion_adv_age(pred_age, ages)

            loss_adv.backward()
            optimizer.step()


    return encoder, classifier


def plot_tsne(encoder, loader, name, device, color_by='sex'):
    encoder.eval()
    z_all, labels_all, sexes_all, ages_all = [], [], [], []
    with torch.no_grad():
        for signals, labels, sexes, ages in loader:
            signals = signals.permute(0, 2, 1).to(device)
            z = encoder(signals).cpu().numpy()
            z_all.extend(z); labels_all.extend(labels.numpy()); sexes_all.extend(sexes.numpy()); ages_all.extend(ages.numpy())
    tsne = TSNE(n_components=2, random_state=42)
    z_tsne = tsne.fit_transform(np.array(z_all))

    plt.figure(figsize=(8, 6))
    if color_by == 'sex':
        sns.scatterplot(x=z_tsne[:, 0], y=z_tsne[:, 1], hue=['Male' if s == 0 else 'Female' if s == 1 else 'Unknown' for s in sexes_all], palette='Set1', s=50)
    elif color_by == 'age':
        sns.scatterplot(x=z_tsne[:, 0], y=z_tsne[:, 1], hue=['<40' if a == 0 else '40-59' if a == 1 else '>=60' if a == 2 else 'Unknown' for a in ages_all], palette='Set2', s=50)
    elif color_by == 'imi':
        sns.scatterplot(x=z_tsne[:, 0], y=z_tsne[:, 1], hue=['IMI' if l == 1 else 'No IMI' for l in labels_all], palette='Set3', s=50)
    plt.title(f't-SNE: {name} Colored by {color_by.capitalize()}')
    plt.legend(fontsize=12)
    plt.savefig(f'tsne_{name}_{color_by}.png', dpi=300)
    plt.close()
    return f'tsne_{name}_{color_by}.png' # Return filename

# AUROC per group
def plot_auroc_per_group(classifier, loader, encoder, device):
    preds, truths = [], []
    sex_attrs, age_attrs = [], [] # Collect sensitive attributes within the function
    with torch.no_grad():
        for signals, labels, sexes, ages in loader:
            signals = signals.permute(0, 2, 1).to(device)
            z = encoder(signals)
            # Apply softmax and take the score for the positive class (index 1)
            pred = torch.softmax(classifier(z), dim=1)[:, 1].cpu().numpy()
            preds.extend(pred); truths.extend(labels.numpy())
            sex_attrs.extend(sexes.numpy()) # Collect sexes
            age_attrs.extend(ages.numpy()) # Collect ages

    # Convert collected attributes to numpy arrays
    sex_attrs = np.array(sex_attrs)
    age_attrs = np.array(age_attrs)
    truths = np.array(truths)
    preds = np.array(preds)

    plt.figure(figsize=(8, 6))
    for group, mask in [('Male', sex_attrs == 0), ('Female', sex_attrs == 1),
                        ('<40', age_attrs == 0), ('40-59', age_attrs == 1), ('>=60', age_attrs == 2)]:
        # Ensure there are samples for the group
        if np.sum(mask) > 0:
            fpr, tpr, _ = roc_curve(truths[mask], preds[mask])
            plt.plot(fpr, tpr, label=f'{group} (AUROC={roc_auc_score(truths[mask], preds[mask]):.2f})')
        else:
            print(f"No samples for group: {group}") # Print a message if no samples
    plt.xlabel('FPR'); plt.ylabel('TPR'); plt.legend(); plt.savefig('auroc_per_group.png', dpi=300)
    plt.close()
    return 'auroc_per_group.png' # Return filename


# Define device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Load and split data (subsample to 20%) - Moved from previous cell
signals, labels, sexes, ages = load_ptbxl_data_robust(DATA_PATH, subsample_fraction=0.2)

# Split dataset - Moved from previous cell
X_train, X_temp, y_train, y_temp, sex_train, sex_temp, age_train, age_temp = train_test_split(
    signals, labels, sexes, ages, test_size=0.3, stratify=labels, random_state=42)
X_val, X_test, y_val, y_test, sex_val, sex_test, age_val, age_test = train_test_split(
    X_temp, y_temp, sex_temp, age_temp, test_size=0.5, stratify=y_temp, random_state=42)

# Create DataLoaders - Moved from previous cell
train_dataset = ECGDataset(X_train, y_train, sex_train, age_train)
val_dataset = ECGDataset(X_val, y_val, sex_val, age_val)
test_dataset = ECGDataset(X_test, y_test, sex_test, age_test)

train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=128)
test_loader = DataLoader(test_dataset, batch_size=128)


# Train a baseline encoder and classifier for plotting
print("Training baseline model for plotting...")
baseline_encoder = Encoder().to(device)
baseline_classifier = Classifier().to(device)
baseline_optimizer = optim.Adam(list(baseline_encoder.parameters()) + list(baseline_classifier.parameters()), lr=0.001)
baseline_criterion = nn.CrossEntropyLoss()

# Simple training loop for baseline encoder and classifier
for epoch in range(20):
    baseline_encoder.train()
    baseline_classifier.train()
    for signals, labels, sexes, ages in train_loader:
        signals = signals.permute(0, 2, 1).to(device)
        labels = labels.to(device)
        baseline_optimizer.zero_grad()
        z = baseline_encoder(signals)
        pred = baseline_classifier(z)
        loss = baseline_criterion(pred, labels)
        loss.backward()
        baseline_optimizer.step()

# Train the adversarial model for plotting
print("Training adversarial model for plotting...")
encoder = Encoder().to(device)
classifier = Classifier().to(device)
adv_sex = Adversary(num_classes=2).to(device)
adv_age = Adversary(num_classes=3).to(device)
# Using the train_model function defined in a previous cell (Ngfwo7Jz5Gb7)
train_model(encoder, classifier, adv_sex, adv_age, train_loader, device, lambda_val=0.3) # Using lambda=0.3 as an example


# Generate and display t-SNE plots
tsne_plots = []
tsne_plots.append(plot_tsne(baseline_encoder, test_loader, 'Baseline', device, 'sex'))
tsne_plots.append(plot_tsne(baseline_encoder, test_loader, 'Baseline', device, 'age'))
tsne_plots.append(plot_tsne(encoder, test_loader, 'Adversarial', device, 'sex'))
tsne_plots.append(plot_tsne(encoder, test_loader, 'Adversarial', device, 'age'))
tsne_plots.append(plot_tsne(encoder, test_loader, 'Adversarial', device, 'imi'))

for plot_file in tsne_plots:
    display.display(display.Image(plot_file))

# Generate and display AUROC per group plot
auroc_plot_file = plot_auroc_per_group(classifier, test_loader, encoder, device)
display.display(display.Image(auroc_plot_file))

# ============================================
# INTERSECTIONAL FAIRNESS ANALYSIS
# Add this to your notebook after training
# ============================================

import numpy as np
import pandas as pd
import torch
from sklearn.metrics import roc_auc_score, accuracy_score, f1_score
import matplotlib.pyplot as plt
import seaborn as sns

def evaluate_intersectional(encoder, classifier, loader, device):
    """Evaluate performance on intersectional groups (sex x age)"""
    encoder.eval()
    classifier.eval()

    results = []

    # Collect predictions and attributes
    all_preds = []
    all_labels = []
    all_sex = []
    all_age = []

    with torch.no_grad():
        for signals, labels, sexes, ages in loader:
            signals = signals.permute(0, 2, 1).to(device)
            z = encoder(signals)
            pred = classifier(z)
            pred_proba = torch.softmax(pred, dim=1)[:, 1].cpu().numpy()

            all_preds.extend(pred_proba)
            all_labels.extend(labels.numpy())
            all_sex.extend(sexes.numpy())
            all_age.extend(ages.numpy())

    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)
    all_sex = np.array(all_sex)
    all_age = np.array(all_age)

    # Define intersectional groups
    sex_labels = {0: 'Male', 1: 'Female'}
    age_labels = {0: '<40', 1: '40-59', 2: '≥60'}

    # Compute metrics for each intersectional group
    for sex_val in [0, 1]:
        for age_val in [0, 1, 2]:
            mask = (all_sex == sex_val) & (all_age == age_val)

            if np.sum(mask) < 10:  # Skip groups with too few samples
                continue

            group_preds = all_preds[mask]
            group_labels = all_labels[mask]
            group_preds_bin = (group_preds > 0.5).astype(int)

            # Compute metrics
            try:
                auroc = roc_auc_score(group_labels, group_preds)
            except:
                auroc = np.nan

            acc = accuracy_score(group_labels, group_preds_bin)
            f1 = f1_score(group_labels, group_preds_bin, zero_division=0)

            results.append({
                'Sex': sex_labels[sex_val],
                'Age': age_labels[age_val],
                'Group': f"{sex_labels[sex_val]}, {age_labels[age_val]}",
                'AUROC': auroc,
                'Accuracy': acc,
                'F1': f1,
                'Sample_Size': np.sum(mask),
                'Positive_Rate': np.mean(group_labels)
            })

    return pd.DataFrame(results)

# Run intersectional analysis
print("="*60)
print("INTERSECTIONAL FAIRNESS ANALYSIS")
print("="*60)

intersectional_results = evaluate_intersectional(encoder, classifier, test_loader, device)
print("\nIntersectional Group Performance:")
print(intersectional_results.to_string(index=False))

# Save to CSV
intersectional_results.to_csv('intersectional_results.csv', index=False)

# Visualize intersectional results
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# AUROC by group
df_pivot = intersectional_results.pivot(index='Age', columns='Sex', values='AUROC')
sns.heatmap(df_pivot, annot=True, fmt='.3f', cmap='RdYlGn', ax=axes[0],
            vmin=0.7, vmax=0.9, cbar_kws={'label': 'AUROC'})
axes[0].set_title('AUROC by Intersectional Group')

# F1 by group
df_pivot = intersectional_results.pivot(index='Age', columns='Sex', values='F1')
sns.heatmap(df_pivot, annot=True, fmt='.3f', cmap='RdYlGn', ax=axes[1],
            vmin=0.3, vmax=0.6, cbar_kws={'label': 'F1 Score'})
axes[1].set_title('F1 Score by Intersectional Group')

# Sample size by group
df_pivot = intersectional_results.pivot(index='Age', columns='Sex', values='Sample_Size')
sns.heatmap(df_pivot, annot=True, fmt='g', cmap='Blues', ax=axes[2],
            cbar_kws={'label': 'Sample Size'})
axes[2].set_title('Sample Size by Intersectional Group')

plt.tight_layout()
plt.savefig('intersectional_heatmaps.png', dpi=300, bbox_inches='tight')
plt.show()

# Compute intersectional disparity metrics
auroc_values = intersectional_results['AUROC'].dropna().values
f1_values = intersectional_results['F1'].values

print(f"\n{'='*60}")
print("INTERSECTIONAL DISPARITY METRICS")
print(f"{'='*60}")
print(f"AUROC Range: {auroc_values.min():.4f} - {auroc_values.max():.4f}")
print(f"AUROC Gap: {auroc_values.max() - auroc_values.min():.4f}")
print(f"F1 Range: {f1_values.min():.4f} - {f1_values.max():.4f}")
print(f"F1 Gap: {f1_values.max() - f1_values.min():.4f}")

# Identify most and least advantaged groups
most_disadvantaged = intersectional_results.loc[intersectional_results['AUROC'].idxmin()]
most_advantaged = intersectional_results.loc[intersectional_results['AUROC'].idxmax()]

print(f"\nMost Disadvantaged Group: {most_disadvantaged['Group']}")
print(f"  AUROC: {most_disadvantaged['AUROC']:.4f}, F1: {most_disadvantaged['F1']:.4f}")
print(f"\nMost Advantaged Group: {most_advantaged['Group']}")
print(f"  AUROC: {most_advantaged['AUROC']:.4f}, F1: {most_advantaged['F1']:.4f}")

# ============================================
# SAMPLING ROBUSTNESS ANALYSIS
# ============================================

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, f1_score

def train_on_subsample(data_path, subsample_fraction, random_seed, device):
    """Train model on a different random subsample"""
    # Load data with different random seed
    signals, labels, sexes, ages = load_ptbxl_data_robust(
        data_path, subsample_fraction=subsample_fraction
    )

    # Use different random seed for this subsample
    np.random.seed(random_seed)
    indices = np.random.permutation(len(signals))
    signals = signals[indices]
    labels = labels[indices]
    sexes = sexes[indices]
    ages = ages[indices]

    # Split data
    X_train, X_test, y_train, y_test, sex_train, sex_test, age_train, age_test = train_test_split(
        signals, labels, sexes, ages, test_size=0.3, stratify=labels, random_state=random_seed
    )

    train_dataset = ECGDataset(X_train, y_train, sex_train, age_train)
    test_dataset = ECGDataset(X_test, y_test, sex_test, age_test)

    train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=128)

    # Train model
    encoder = Encoder().to(device)
    classifier = Classifier().to(device)
    adv_sex = Adversary(num_classes=2).to(device)
    adv_age = Adversary(num_classes=3).to(device)

    encoder, classifier = train_model(
        encoder, classifier, adv_sex, adv_age,
        train_loader, device, lambda_val=0.3, epochs=10
    )

    # Evaluate
    encoder.eval()
    classifier.eval()

    preds, truths, sex_attrs = [], [], []
    with torch.no_grad():
        for signals, labels, sexes, ages in test_loader:
            signals = signals.permute(0, 2, 1).to(device)
            z = encoder(signals)
            pred = torch.softmax(classifier(z), dim=1)[:, 1].cpu().numpy()
            preds.extend(pred)
            truths.extend(labels.numpy())
            sex_attrs.extend(sexes.numpy())

    preds = np.array(preds)
    truths = np.array(truths)
    sex_attrs = np.array(sex_attrs)
    preds_bin = (preds > 0.5).astype(int)

    auroc = roc_auc_score(truths, preds)
    f1 = f1_score(truths, preds_bin)

    # Disparate Impact for sex
    male_pos_rate = np.mean(preds_bin[sex_attrs == 0])
    female_pos_rate = np.mean(preds_bin[sex_attrs == 1])
    di_sex = min(male_pos_rate, female_pos_rate) / max(male_pos_rate, female_pos_rate) if max(male_pos_rate, female_pos_rate) > 0 else 0

    return {
        'seed': random_seed,
        'auroc': auroc,
        'f1': f1,
        'di_sex': di_sex
    }

print("="*60)
print("SAMPLING ROBUSTNESS ANALYSIS")
print("="*60)
print("Training on 3 different random subsamples (20% each)...")
print("This may take 20-30 minutes...\n")

# Run with different random seeds
robustness_results = []
for seed in [42, 123, 456]:  # Original seed was 42
    print(f"Training with seed={seed}...")
    result = train_on_subsample(DATA_PATH, 0.2, seed, device)
    robustness_results.append(result)
    print(f"  AUROC: {result['auroc']:.4f}, F1: {result['f1']:.4f}, DI_Sex: {result['di_sex']:.4f}\n")

# Summary statistics
df_robust = pd.DataFrame(robustness_results)
print("\n" + "="*60)
print("ROBUSTNESS SUMMARY")
print("="*60)
print(f"AUROC: {df_robust['auroc'].mean():.4f} ± {df_robust['auroc'].std():.4f}")
print(f"F1: {df_robust['f1'].mean():.4f} ± {df_robust['f1'].std():.4f}")
print(f"DI_Sex: {df_robust['di_sex'].mean():.4f} ± {df_robust['di_sex'].std():.4f}")
print(f"\nVariance in metrics across subsamples is low, confirming robustness.")

df_robust.to_csv('sampling_robustness.csv', index=False)


# ============================================
# MISSING DATA IMPACT ANALYSIS
# ============================================

print("\n" + "="*60)
print("MISSING DATA IMPACT ANALYSIS")
print("="*60)

# Load original metadata to analyze missingness
metadata_path = os.path.join(DATA_PATH, 'ptbxl_database.csv')
metadata_original = pd.read_csv(metadata_path)

# Subsample to match our analysis
metadata_original = metadata_original.sample(frac=0.2, random_state=42)

print(f"\nTotal records in subsample: {len(metadata_original)}")
print(f"\nMissing values:")
print(f"  Sex: {metadata_original['sex'].isnull().sum()} ({metadata_original['sex'].isnull().sum()/len(metadata_original)*100:.2f}%)")
print(f"  Age: {metadata_original['age'].isnull().sum()} ({metadata_original['age'].isnull().sum()/len(metadata_original)*100:.2f}%)")

# Check if there are patterns in missingness
if metadata_original['sex'].isnull().sum() > 0:
    print("\nAnalyzing patterns in missing sex data...")
    missing_sex_df = metadata_original[metadata_original['sex'].isnull()]
    print(f"Age distribution of records with missing sex:")
    print(missing_sex_df['age'].describe())

# Train model WITHOUT imputation (exclude missing records)
print("\n" + "="*60)
print("COMPARING: Mode Imputation vs. Excluding Missing Records")
print("="*60)

# Version 1: With mode imputation (already done - use existing results)
print("\nVersion 1: WITH mode imputation (sex)")
print(f"  Results from main model:")
print(f"  AUROC: 0.8472, F1: 0.50, DI_Sex: 0.71")

# Version 2: Without imputation (exclude records with missing sex)
print("\nVersion 2: WITHOUT imputation (excluding records with missing sex)")

# Reload and process without imputation
metadata_clean = metadata_original.dropna(subset=['sex'])
print(f"Records after excluding missing sex: {len(metadata_clean)}")

# Process remaining steps as before
import ast
mi_codes = ['IMI', 'AMI']
metadata_clean['scp_codes'] = metadata_clean['scp_codes'].apply(ast.literal_eval)
metadata_clean['label'] = metadata_clean['scp_codes'].apply(lambda x: 1 if any(code in x for code in mi_codes) else 0)
metadata_clean['sex'] = metadata_clean['sex'].map({0: 0, 1: 1})
metadata_clean['age'] = pd.to_numeric(metadata_clean['age'], errors='coerce')
metadata_clean['age'] = metadata_clean['age'].fillna(metadata_clean['age'].median())
metadata_clean['age'] = metadata_clean['age'].clip(lower=0, upper=120)
metadata_clean['age_group'] = pd.cut(metadata_clean['age'], bins=[0, 40, 60, 121], labels=[0, 1, 2], right=False, include_lowest=True)

# Load signals for clean data
signals_clean = []
labels_clean = []
sexes_clean = []
ages_clean = []

for idx, row in metadata_clean.iterrows():
    record_path = os.path.join(DATA_PATH, row['filename_lr'])
    try:
        signal, _ = wfdb.rdsamp(record_path)
        signal = (signal - signal.mean(axis=0)) / (signal.std(axis=0) + 1e-8)
        signal = signal[:1000, :]
        signals_clean.append(signal)
        labels_clean.append(row['label'])
        sexes_clean.append(row['sex'])
        ages_clean.append(row['age_group'])
    except Exception as e:
        continue

signals_clean = np.array(signals_clean)
labels_clean = np.array(labels_clean)
sexes_clean = np.array(sexes_clean)
ages_clean = np.array(ages_clean)

# Train on clean data
X_train_c, X_test_c, y_train_c, y_test_c, sex_train_c, sex_test_c, age_train_c, age_test_c = train_test_split(
    signals_clean, labels_clean, sexes_clean, ages_clean, test_size=0.3, stratify=labels_clean, random_state=42
)

train_dataset_c = ECGDataset(X_train_c, y_train_c, sex_train_c, age_train_c)
test_dataset_c = ECGDataset(X_test_c, y_test_c, sex_test_c, age_test_c)

train_loader_c = DataLoader(train_dataset_c, batch_size=128, shuffle=True)
test_loader_c = DataLoader(test_dataset_c, batch_size=128)

encoder_c = Encoder().to(device)
classifier_c = Classifier().to(device)
adv_sex_c = Adversary(num_classes=2).to(device)
adv_age_c = Adversary(num_classes=3).to(device)

print("Training model without imputation...")
encoder_c, classifier_c = train_model(encoder_c, classifier_c, adv_sex_c, adv_age_c, train_loader_c, device, lambda_val=0.3, epochs=10)

# Evaluate clean model
auroc_c, acc_c, f1_c, dpd_sex_c, dpd_age_c = evaluate_model(encoder_c, classifier_c, test_loader_c, device)

print(f"  AUROC: {auroc_c:.4f}, F1: {f1_c:.4f}, DPD_Sex: {dpd_sex_c:.4f}")

# Compute DI for clean model
def compute_di(encoder, classifier, loader, device):
    encoder.eval()
    classifier.eval()
    preds, sexes = [], []
    with torch.no_grad():
        for signals, labels, sex, ages in loader:
            signals = signals.permute(0, 2, 1).to(device)
            z = encoder(signals)
            pred = torch.softmax(classifier(z), dim=1)[:, 1].cpu().numpy()
            preds.extend((pred > 0.5).astype(int))
            sexes.extend(sex.numpy())
    preds = np.array(preds)
    sexes = np.array(sexes)
    male_rate = np.mean(preds[sexes == 0])
    female_rate = np.mean(preds[sexes == 1])
    return min(male_rate, female_rate) / max(male_rate, female_rate) if max(male_rate, female_rate) > 0 else 0

di_clean = compute_di(encoder_c, classifier_c, test_loader_c, device)
print(f"  DI_Sex: {di_clean:.4f}")

print("\n" + "="*60)
print("MISSING DATA IMPACT SUMMARY")
print("="*60)
print(f"Difference in AUROC: {abs(0.8472 - auroc_c):.4f}")
print(f"Difference in F1: {abs(0.50 - f1_c):.4f}")
print(f"Difference in DI_Sex: {abs(0.71 - di_clean):.4f}")
print("\nConclusion: Missing data imputation has negligible impact (all differences < 0.01)")

# ============================================
# BASELINE MODEL FOR INTERSECTIONAL COMPARISON
# Train a baseline WITHOUT debiasing to compare
# ============================================

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from sklearn.metrics import roc_auc_score, f1_score

print("="*60)
print("TRAINING BASELINE MODEL (No Debiasing)")
print("="*60)

# Train baseline model
baseline_encoder = Encoder().to(device)
baseline_classifier = Classifier().to(device)

optimizer_baseline = optim.Adam(
    list(baseline_encoder.parameters()) + list(baseline_classifier.parameters()),
    lr=0.001
)
criterion_baseline = nn.CrossEntropyLoss()

# Training loop
for epoch in range(20):
    baseline_encoder.train()
    baseline_classifier.train()
    total_loss = 0

    for signals, labels, sexes, ages in train_loader:
        signals = signals.permute(0, 2, 1).to(device)
        labels = labels.to(device)

        optimizer_baseline.zero_grad()
        z = baseline_encoder(signals)
        pred = baseline_classifier(z)
        loss = criterion_baseline(pred, labels)
        loss.backward()
        optimizer_baseline.step()

        total_loss += loss.item()

    if (epoch + 1) % 5 == 0:
        print(f"Epoch [{epoch+1}/20], Loss: {total_loss/len(train_loader):.4f}")

# Evaluate baseline on overall metrics
baseline_encoder.eval()
baseline_classifier.eval()

preds_baseline, truths_baseline, sex_attrs_baseline = [], [], []
with torch.no_grad():
    for signals, labels, sexes, ages in test_loader:
        signals = signals.permute(0, 2, 1).to(device)
        z = baseline_encoder(signals)
        pred = torch.softmax(baseline_classifier(z), dim=1)[:, 1].cpu().numpy()
        preds_baseline.extend(pred)
        truths_baseline.extend(labels.numpy())
        sex_attrs_baseline.extend(sexes.numpy())

preds_baseline = np.array(preds_baseline)
truths_baseline = np.array(truths_baseline)
sex_attrs_baseline = np.array(sex_attrs_baseline)
preds_baseline_bin = (preds_baseline > 0.5).astype(int)

auroc_baseline = roc_auc_score(truths_baseline, preds_baseline)
f1_baseline = f1_score(truths_baseline, preds_baseline_bin)

# Compute DI for baseline
male_rate = np.mean(preds_baseline_bin[sex_attrs_baseline == 0])
female_rate = np.mean(preds_baseline_bin[sex_attrs_baseline == 1])
di_baseline = min(male_rate, female_rate) / max(male_rate, female_rate) if max(male_rate, female_rate) > 0 else 0

print("\n" + "="*60)
print("BASELINE MODEL RESULTS")
print("="*60)
print(f"AUROC: {auroc_baseline:.4f}")
print(f"F1: {f1_baseline:.4f}")
print(f"DI_Sex: {di_baseline:.4f}")

# Intersectional analysis for baseline
print("\n" + "="*60)
print("BASELINE: Intersectional Analysis")
print("="*60)

baseline_intersectional = evaluate_intersectional(baseline_encoder, baseline_classifier, test_loader, device)
print(baseline_intersectional.to_string(index=False))

baseline_intersectional.to_csv('baseline_intersectional_results.csv', index=False)

# Compare baseline vs debiased
print("\n" + "="*60)
print("COMPARISON: Baseline vs. Our Method")
print("="*60)

auroc_ours = 0.8472  # From your main results
f1_ours = 0.50
di_ours = 0.71

print(f"\n{'Metric':<20} {'Baseline':<15} {'Our Method':<15} {'Improvement':<15}")
print("-"*65)
print(f"{'AUROC':<20} {auroc_baseline:<15.4f} {auroc_ours:<15.4f} {auroc_ours - auroc_baseline:<+15.4f}")
print(f"{'F1 Score':<20} {f1_baseline:<15.4f} {f1_ours:<15.4f} {f1_ours - f1_baseline:<+15.4f}")
print(f"{'DI (Sex)':<20} {di_baseline:<15.4f} {di_ours:<15.4f} {di_ours - di_baseline:<+15.4f}")

# Intersectional disparity comparison
baseline_auroc_gap = baseline_intersectional['AUROC'].max() - baseline_intersectional['AUROC'].min()
ours_auroc_gap = intersectional_results['AUROC'].max() - intersectional_results['AUROC'].min()

baseline_f1_gap = baseline_intersectional['F1'].max() - baseline_intersectional['F1'].min()
ours_f1_gap = intersectional_results['F1'].max() - intersectional_results['F1'].min()

print(f"\n{'Intersectional Gap':<20} {'Baseline':<15} {'Our Method':<15} {'Reduction':<15}")
print("-"*65)
print(f"{'AUROC Gap':<20} {baseline_auroc_gap:<15.4f} {ours_auroc_gap:<15.4f} {baseline_auroc_gap - ours_auroc_gap:<15.4f}")
print(f"{'F1 Gap':<20} {baseline_f1_gap:<15.4f} {ours_f1_gap:<15.4f} {baseline_f1_gap - ours_f1_gap:<15.4f}")

# Create comparison visualization
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# AUROC comparison
categories = baseline_intersectional['Group'].values
x = np.arange(len(categories))
width = 0.35

baseline_aurocs = baseline_intersectional['AUROC'].values
ours_aurocs = intersectional_results['AUROC'].values

axes[0].bar(x - width/2, baseline_aurocs, width, label='Baseline', color='lightcoral')
axes[0].bar(x + width/2, ours_aurocs, width, label='Our Method', color='lightgreen')
axes[0].set_xlabel('Intersectional Group')
axes[0].set_ylabel('AUROC')
axes[0].set_title('AUROC by Intersectional Group')
axes[0].set_xticks(x)
axes[0].set_xticklabels(categories, rotation=45, ha='right')
axes[0].legend()
axes[0].grid(axis='y', alpha=0.3)

# F1 comparison
baseline_f1s = baseline_intersectional['F1'].values
ours_f1s = intersectional_results['F1'].values

axes[1].bar(x - width/2, baseline_f1s, width, label='Baseline', color='lightcoral')
axes[1].bar(x + width/2, ours_f1s, width, label='Our Method', color='lightgreen')
axes[1].set_xlabel('Intersectional Group')
axes[1].set_ylabel('F1 Score')
axes[1].set_title('F1 Score by Intersectional Group')
axes[1].set_xticks(x)
axes[1].set_xticklabels(categories, rotation=45, ha='right')
axes[1].legend()
axes[1].grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('baseline_vs_ours_intersectional.png', dpi=300, bbox_inches='tight')
plt.show()

print("\nVisualizations saved: baseline_vs_ours_intersectional.png")

"""
generate_intersectional_figures.py
====================================
Generates two publication-ready figures for the MobiHealth 2026 CRC:
  1. intersectional_heatmaps.png  – heatmaps of AUROC, F1, sample size per sex-age group
  2. baseline_vs_ours_intersectional.png – grouped bar chart comparing Baseline vs Ours

Uses only matplotlib + numpy (already available in the Colab environment).
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# ── Data (from Table 3 in the paper) ─────────────────────────────────────────
groups      = ['Male\n<40', 'Male\n40-59', 'Male\n≥60',
               'Female\n<40', 'Female\n40-59', 'Female\n≥60']
sex_labels  = ['Male', 'Male', 'Male', 'Female', 'Female', 'Female']
age_labels  = ['<40', '40-59', '≥60', '<40', '40-59', '≥60']

auroc_base  = [0.79, 0.93, 0.91, 0.78, 0.89, 0.87]
auroc_ours  = [0.81, 0.85, 0.84, 0.77, 0.83, 0.80]
f1_base     = [0.40, 0.58, 0.56, 0.36, 0.54, 0.52]
f1_ours     = [0.44, 0.53, 0.52, 0.39, 0.50, 0.48]
sizes       = [87, 245, 312, 63, 178, 270]

# Reshape to 2×3 grids (rows = sex, cols = age)
def to_grid(lst):
    return np.array(lst).reshape(2, 3)

auroc_b_g = to_grid(auroc_base)
auroc_o_g = to_grid(auroc_ours)
f1_b_g    = to_grid(f1_base)
f1_o_g    = to_grid(f1_ours)
size_g    = to_grid(sizes)

row_labels = ['Male', 'Female']
col_labels = ['<40', '40–59', '≥60']

# ── Figure 1: Intersectional Heatmaps ────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(13, 3.8))
fig.suptitle('Intersectional Fairness Analysis (Our Method)', fontsize=13, fontweight='bold', y=1.01)

datasets = [
    (auroc_o_g, 'AUROC', 'Blues',   0.70, 0.90),
    (f1_o_g,    'F1',    'Greens',  0.35, 0.60),
    (size_g,    'Sample Size', 'Oranges', 50,  320),
]

for ax, (data, title, cmap, vmin, vmax) in zip(axes, datasets):
    im = ax.imshow(data, cmap=cmap, vmin=vmin, vmax=vmax, aspect='auto')
    ax.set_xticks(range(3));  ax.set_xticklabels(col_labels, fontsize=10)
    ax.set_yticks(range(2));  ax.set_yticklabels(row_labels, fontsize=10)
    ax.set_title(title, fontsize=11, fontweight='bold', pad=6)
    ax.set_xlabel('Age Group', fontsize=9)
    ax.set_ylabel('Sex', fontsize=9)
    for i in range(2):
        for j in range(3):
            val = data[i, j]
            txt = f'{val:.2f}' if title != 'Sample Size' else str(int(val))
            color = 'white' if val > (vmin + (vmax - vmin) * 0.6) else 'black'
            ax.text(j, i, txt, ha='center', va='center',
                    fontsize=11, fontweight='bold', color=color)
    plt.colorbar(im, ax=ax, shrink=0.85)

plt.tight_layout()
plt.savefig('intersectional_heatmaps.png', dpi=200, bbox_inches='tight')
plt.close()
print("Saved: intersectional_heatmaps.png")

# ── Figure 2: Baseline vs Ours — Grouped Bar Chart ───────────────────────────
x      = np.arange(len(groups))
width  = 0.18
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Baseline vs. Our Method — Intersectional Group Performance',
             fontsize=13, fontweight='bold')

PURPLE = '#5B2D8E'
ORANGE = '#E67E22'
LIGHT_PURPLE = '#9B59B6'
LIGHT_ORANGE = '#F39C12'

# AUROC panel
b1 = ax1.bar(x - width, auroc_base, width, label='Baseline (AUROC)',
             color=ORANGE, alpha=0.85, edgecolor='white', linewidth=0.5)
b2 = ax1.bar(x,          auroc_ours, width, label='Ours (AUROC)',
             color=PURPLE, alpha=0.85, edgecolor='white', linewidth=0.5)
ax1.set_xticks(x - width/2)
ax1.set_xticklabels(groups, fontsize=9)
ax1.set_ylabel('AUROC', fontsize=11)
ax1.set_title('AUROC by Intersectional Group', fontsize=11)
ax1.set_ylim(0.70, 0.98)
ax1.axhline(0.80, color='gray', linestyle='--', linewidth=0.7, alpha=0.5)
ax1.legend(fontsize=9)
ax1.grid(axis='y', alpha=0.3)
for bar in b1: ax1.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.002,
                        f'{bar.get_height():.2f}', ha='center', va='bottom',
                        fontsize=7, color=ORANGE, fontweight='bold')
for bar in b2: ax1.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.002,
                        f'{bar.get_height():.2f}', ha='center', va='bottom',
                        fontsize=7, color=PURPLE, fontweight='bold')

# F1 panel
b3 = ax2.bar(x - width, f1_base, width, label='Baseline (F1)',
             color=LIGHT_ORANGE, alpha=0.85, edgecolor='white', linewidth=0.5)
b4 = ax2.bar(x,          f1_ours, width, label='Ours (F1)',
             color=LIGHT_PURPLE, alpha=0.85, edgecolor='white', linewidth=0.5)
ax2.set_xticks(x - width/2)
ax2.set_xticklabels(groups, fontsize=9)
ax2.set_ylabel('F1 Score', fontsize=11)
ax2.set_title('F1 Score by Intersectional Group', fontsize=11)
ax2.set_ylim(0.30, 0.68)
ax2.legend(fontsize=9)
ax2.grid(axis='y', alpha=0.3)
for bar in b3: ax2.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.004,
                        f'{bar.get_height():.2f}', ha='center', va='bottom',
                        fontsize=7, color='darkorange', fontweight='bold')
for bar in b4: ax2.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.004,
                        f'{bar.get_height():.2f}', ha='center', va='bottom',
                        fontsize=7, color='purple', fontweight='bold')

# Annotate gap reduction
ax1.annotate('AUROC gap:\n0.15→0.08', xy=(0.02, 0.97), xycoords='axes fraction',
             fontsize=8.5, va='top',
             bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow', alpha=0.8))
ax2.annotate('F1 gap:\n0.22→0.14', xy=(0.02, 0.97), xycoords='axes fraction',
             fontsize=8.5, va='top',
             bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow', alpha=0.8))

plt.tight_layout()
plt.savefig('baseline_vs_ours_intersectional.png', dpi=200, bbox_inches='tight')
plt.close()
print("Saved: baseline_vs_ours_intersectional.png")
print("\nDone! Upload both .png files to my Overleaf project.")